modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="materialchanger" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Material Changer" #mandatory
credits="The Forge and FML guys and Lellson for making Material Changer" #optional
authors="Lellson 1.12.2, 1.11.2, and 1.10.2 RedRoseWarrior1 1.14.4+" #optional
description='''
Allows you to change various attributes of weapons, tools and armor
'''
[[dependencies.materialchanger]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"

    side="BOTH"
[[dependencies.materialchanger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
